name: Extensions Overview

on:
  push:
    branches:
      - extensions

jobs:
  list:
    runs-on: linux-latest

    steps:
      - uses: aliasadidev/vscode-npm-gui@v2.0.6
      - uses: bscan/PerlNavigator@v0.7.13
      - uses: ChristianKohler/PathIntellisense@v2.8.0
      - uses: DavidAnson/vscode-markdownlint@v0.54.0
      - uses: DonJayamanne/gitHistoryVSCode@v0.6.20
      - uses: formulahendry/vscode-auto-close-tag@0.5.5
      - uses: gitkraken/vscode-gitlens@v14.7.0
      - uses: glideapps/quicktype@v7.0.0
      - uses: Gruntfuggly/todo-tree
      - uses: jdinhify/vscode-theme-gruvbox@v1.17.0
      - uses: mhutchie/vscode-git-graph@v1.30.0
      - uses: microsoft/pylance-release
      - uses: microsoft/vscode-notepadplusplus-keybindings@v1.0.3
      - uses: microsoft/vscode-python@v2023.22.1
      - uses: MicrosoftDocs/intellicode
      - uses: mikestead/vscode-dotenv@v1.0.1
      - uses: oderwat/vscode-indent-rainbow
      - uses: pester/vscode-adapter@v2023.7.7
      - uses: PowerShell/vscode-powershell@v2024.0.0
      - uses: prettier/prettier-vscode@v10.1.0
      - uses: rangav/thunder-client-support@v2.17.0
      - uses: redhat-developer/vscode-redhat-account@v0.0.7
      - uses: redhat-developer/vscode-yaml@1.14.0
      - uses: shardulm94/vscode-trailingspaces@v0.4.1
      - uses: streetsidesoftware/vscode-spell-checker@code-spell-checker-v3.0.1
      - uses: Tyriar/vscode-shell-launcher
      - uses: vincaslt/vscode-highlight-matching-tag
      - uses: vivaxy/vscode-conventional-commits@v1.25.0
      - uses: vscode-icons/vscode-icons@v12.7.0
      - uses: vscode-kubernetes-tools/vscode-kubernetes-tools@1.3.15
      - uses: yzhang-gh/vscode-markdown@v3.4.0