name: Visual Studio Code Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Print working directory
        run: pwd
      - name: List directory content
        run: dir

      # Download vscode zip
      - name: Download vscode archive
        run: ./Download-VSCodex64Archive.ps1
      - name: Move file to data directory
        run: |
          mkdir vscode_zip
          mv VSCode*.zip vscode_zip

      # - name: Download vscode install script
      #   run: Invoke-WebRequest https://raw.githubusercontent.com/PowerShell/vscode-powershell/main/scripts/Install-VSCode.ps1 -Outfile Install-VSCode.ps1

      # Download and Install VS Code and extensions on Windows
      - name: Download and install
        run: ./Install-VSCodeExtensions.ps1 -AdditionalExtensions $((Get-Content ./package-lock.json | ConvertFrom-Json).extensions.uid)

      # Create archive of extension archives including vscode zip
      #      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'


      # - name: Download Visual Studio Code
        # run: ./Download-VSCodex64Archive.ps1
          # |
          # $current_directory = pwd
          # Get-ChildItem -Path $current_directory
#          tar -xf vscode.tar.gz
#          ls -la
#          sudo mv vscode-* /usr/share/code

#      - name: Download Extensions
#        run: |
#          $extensions = @("extension1@version1", "extension2@version2")
#          foreach ($ext in $extensions) {
#            code-server --install-extension $ext
#         }
       # Füge hier weitere Code-Zeilen hinzu, um zusätzliche Extensions herunterzuladen


      - name: Archive Data Directory
        uses: actions/upload-artifact@v3
        with:
         name: data-artifact
         path: vscode_zip

#      - name: List directory contents
#        run: |
#          pwd
#          ls -la

## save name of extensions and their (and vscodes) version number in a file
## run pipeline daily
## check and mail if version was incremented
