name: Visual Studio Code Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Download and Install VS Code on Windows
      # Install specific extensions in VS Code
      # Create archive for each extension
      # Download vscode zip
      # Create archive of extension archives including vscode zip

      #      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
      - uses: actions/checkout

      - name: Print working directory
        run: pwd

      - name: List directory content
        run: dir

      # - name: Download Visual Studio Code
        # run: ./Download-VSCodex64Archive.ps1
          # |
          # $current_directory = pwd
          # Get-ChildItem -Path $current_directory
#          tar -xf vscode.tar.gz
#          ls -la
#          sudo mv vscode-* /usr/share/code

#      - name: Download Extensions
#        run: |
#          $extensions = @("extension1@version1", "extension2@version2")
#          foreach ($ext in $extensions) {
#            code-server --install-extension $ext
#         }
       # Füge hier weitere Code-Zeilen hinzu, um zusätzliche Extensions herunterzuladen


#      - name: Archive Data Directory
#        uses: actions/upload-artifact@v2
#        with:
#          name: data-artifact
#          path: /path/to/data/directory

#      - name: List directory contents
#        run: |
#          pwd
#          ls -la
