name: Visual Studio Code Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 5 * * * # TZ=UTC

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # - name: Print working directory
      #   run: pwd
      # - name: List directory content
      #   run: dir
      # - name: Save tree file for C to artifact
      #   run: powershell -command "tree /f /a c:\ > vscode/tree_C.txt"
      # - name: Save tree file for D to artifact
      #   run: powershell -command "tree /f /a d:\ > vscode/tree_D.txt"

      # Get current release version
      - name: Get current release version
        id: current_release
        run: echo "current_release_version=$(`"$((Get-Content ./release_version.json | ConvertFrom-Json).appVersion)-$((Get-Content ./release_version.json | ConvertFrom-Json).iteration)`")" >> $env:GITHUB_OUTPUT

      # Download vscode zip
      - name: Download vscode archive
        run: ./scripts/Download-VSCodex64Archive.ps1
      - name: Move file to data directory
        run: |
          mkdir -p vscode\extensions
          mv VSCode*.zip vscode

      # - name: Download vscode install script
      #   run: Invoke-WebRequest https://raw.githubusercontent.com/PowerShell/vscode-powershell/main/scripts/Install-VSCode.ps1 -Outfile Install-VSCode.ps1

      # Download and Install VS Code and extensions on Windows
      - name: Download and install
        run: ./scripts/Install-VSCodeExtensions.ps1 -AdditionalExtensions $((Get-Content ./extensions.json | ConvertFrom-Json).extensions.uid) -BuildEdition 'Stable-User'

      - name: Archive extensions and update extensions.json
        run: echo "new_release_version=$(./scripts/Archive-VSCodeExtensions.ps1)" >> $env:GITHUB_OUTPUT
        id: archive_extensions

      # - name: Generate version
      #   run: echo "{version}={$((Get-Content ./release_version.json | ConvertFrom-Json).applications[0].version)}" >> $GITHUB_OUTPUT
      #   id: generate_version

      - name: List release versions
        run: |
          echo "Current Release: ${{ steps.current_release.outputs.current_release_version }}"
          echo "New Release: ${{ steps.archive_extensions.outputs.new_release_version }}"

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.archive_extensions.outputs.new_release_version }}
          tag_name: ${{ steps.archive_extensions.outputs.new_release_version }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: ne(${{ steps.current_release.outputs.current_release_version }}, ${{ steps.archive_extensions.outputs.new_release_version }})

      - name: upload artifact as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vscode/vscode_with_extensions.zip
          asset_name: vscode_with_extensions.zip
          asset_content_type: application/zip
        if: ne(${{ steps.current_release.outputs.current_release_version }}, ${{ steps.archive_extensions.outputs.new_release_version }})

      # - name: Archive Data Directory
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: data-artifact
      #     path: vscode
  
      - name: Remove artifact directory
        run: |
          Remove-Item -recurse -force vscode
          Remove-Item vscode_with_extensions.zip
  
      # - name: List directory tree
      #   run: tree /f /a
  
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  