name: Visual Studio Code Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'

      - name: Install Visual Studio Code
        run: |
          curl -O 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-archive'
          ls -la
#          tar -xf vscode.tar.gz
#          ls -la
#          sudo mv vscode-* /usr/share/code

#      - name: Install Extensions
#        run: |
#          code-server --install-extension extension1
#          code-server --install-extension extension2

#      - name: Archive Data Directory
#        uses: actions/upload-artifact@v2
#        with:
#          name: data-artifact
#          path: /path/to/data/directory

      - name: List directory contents
        run: |
          pwd
          ls -la
